In [1]:
import pandas as pd
import requests

# Fetch the data.
df = pd.read_csv("https://ourworldindata.org/grapher/life-expectancy.csv?v=1&csvType=full&useColumnShortNames=true", storage_options = {'User-Agent': 'Our World In Data data fetch/1.0'})

# Fetch the metadata
metadata = requests.get("https://ourworldindata.org/grapher/life-expectancy.metadata.json?v=1&csvType=full&useColumnShortNames=true").json()

In [2]:
df.head()

        entity code  year  life_expectancy_0
0  Afghanistan  AFG  1950            28.1563
1  Afghanistan  AFG  1951            28.5836
2  Afghanistan  AFG  1952            29.0138
3  Afghanistan  AFG  1953            29.4521
4  Afghanistan  AFG  1954            29.6975

In [3]:
df.shape

(21565, 4)

In [4]:
df.columns.tolist()

['entity', 'code', 'year', 'life_expectancy_0']

In [5]:
df.dtypes

entity                   str
code                     str
year                   int64
life_expectancy_0    float64
dtype: object

In [6]:
df.isnull().sum()

entity                  0
code                 1348
year                    0
life_expectancy_0       0
dtype: int64

In [7]:
df.describe()

               year  life_expectancy_0
count  21565.000000       21565.000000
mean    1976.992812          61.942232
std       38.461606          12.925912
min     1543.000000          10.989100
25%     1962.000000          52.703000
50%     1982.000000          64.479900
75%     2003.000000          71.978900
max     2023.000000          86.372400

In [35]:
df.rename(columns={"entity" : "pais"},inplace=True)

In [36]:
df_expectancy = df[(df["year"] == 1970) & (df["pais"].str.contains("^K", regex=True))]

print(df_expectancy)

            pais      code  year  life_expectancy_0
9591  Kazakhstan       KAZ  1970            60.0490
9668       Kenya       KEN  1970            54.1427
9742    Kiribati       KIR  1970            54.3802
9816      Kosovo  OWID_KOS  1970            54.0023
9891      Kuwait       KWT  1970            67.9771
9965  Kyrgyzstan       KGZ  1970            58.1840

In [37]:
df.loc[df["code"].isnull()]

                                        pais code  year  life_expectancy_0
375                                 Americas  NaN  1770            34.8000
376                                 Americas  NaN  1830            34.8000
377                                 Americas  NaN  1850            35.1000
378                                 Americas  NaN  1870            35.1000
379                                 Americas  NaN  1900            41.0000
...                                      ...  ...   ...                ...
17703  Small Island Developing States (SIDS)  NaN  2019            72.0847
17704  Small Island Developing States (SIDS)  NaN  2020            71.7761
17705  Small Island Developing States (SIDS)  NaN  2021            69.8938
17706  Small Island Developing States (SIDS)  NaN  2022            72.1257
17707  Small Island Developing States (SIDS)  NaN  2023            72.7255

[1348 rows x 4 columns]

In [38]:
df.loc[df["code"].notnull(),["pais"]].head(3)

          pais
0  Afghanistan
1  Afghanistan
2  Afghanistan

In [39]:
df.set_index("Pais")

KeyError: "None of ['Pais'] are in the columns"

In [40]:
df.dropna(subset=["code"], inplace=True)
df.isnull().sum()

pais                 0
code                 0
year                 0
life_expectancy_0    0
dtype: int64

In [41]:
df.shape

(20217, 4)

In [46]:
resultado = (
    df.groupby("pais")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)
resultado.head(10)

pais
USSR                        32.700000
South Sudan                 37.841631
Sierra Leone                43.189605
Mali                        43.760793
Niger                       44.187513
East Timor                  44.684692
Nigeria                     44.855897
Chad                        45.007786
Central African Republic    45.084431
Malawi                      45.554985
Name: life_expectancy_0, dtype: float64

In [48]:
year_df = df[(df["year"] >= 1970) & (df["year"]<= 2023)]
print(year_df)

              pais code  year  life_expectancy_0
20     Afghanistan  AFG  1970            37.4601
21     Afghanistan  AFG  1971            37.9324
22     Afghanistan  AFG  1972            38.4226
23     Afghanistan  AFG  1973            38.9510
24     Afghanistan  AFG  1974            39.4687
...            ...  ...   ...                ...
21560     Zimbabwe  ZWE  2019            61.0603
21561     Zimbabwe  ZWE  2020            61.5300
21562     Zimbabwe  ZWE  2021            60.1347
21563     Zimbabwe  ZWE  2022            62.3601
21564     Zimbabwe  ZWE  2023            62.7748

[13284 rows x 4 columns]

In [57]:
resultado = (
    year_df.groupby("pais")["life_expectancy_0"]
    .mean()
    .sort_values(ascending=True)
)

print(resultado)

pais
South Sudan                 41.076146
Central African Republic    47.109006
Sierra Leone                47.234867
Chad                        47.391891
Niger                       47.716867
                              ...
Switzerland                 79.105678
San Marino                  79.849424
Japan                       79.861796
Andorra                     80.412854
Monaco                      80.541217
Name: life_expectancy_0, Length: 246, dtype: float64